version: '3.8'

services:
  node-app:
    # --- CHANGE START ---
    # The build context should now be the current directory (where docker-compose.yml is)
    build:
      context: .
      # Explicitly specify the Dockerfile name if it's not simply 'Dockerfile'
      dockerfile: Dockerfile
    # --- CHANGE END ---
    ports:
      - "3000:3000"
    volumes:
      # Mount the entire SHOP-PROJECT directory from your host to /app in the container.
      - .:/app
      # Create an anonymous volume for node_modules inside the container.
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER:-user}
      DB_NAME: ${POSTGRES_DB:-mydatabase}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_PORT: 5432
      PORT: 3000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: